settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mail-code-tech-us-uk # unique identifier
    name: Tmp Email
    description: 'Tmp Email for Personal' # default=empty
    url: 'https://mail.code-tech.us.kg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: banner-c0despace-uk
    name: banner.c0despace.uk
    description: 'Banner for personal'
    url: 'https://banner.c0despace.uk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false

  - id: github-blog
    name: Github BLog
    description: 'Github pages Blog'
    url: 'https://zywj0han9.github.io'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false

  - id: CF-blog
    name: Cloudflare BLog
    description: 'Cloudflare pages Blog'
    url: 'https://blog.zywj0han9.win'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false
