settings:
  title: 'Status Page'
  # url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 180 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'
  
monitors:

  - id: Banner-c0despace
    name: 导航页
    description: '导航页'
    url: 'https://banner.c0despace.uk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false

  - id: Tmpmail-code-tech # unique identifier
    name: 临时邮箱
    description: '临时邮箱' # default=empty
    url: 'https://mail.code-tech.us.kg/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false

  - id: Git-Proxy
    name: Github 加速
    description: 'Github 加速'
    url: 'https://git.c0despace.uk/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: Github-Blog
    name: Github 博客
    description: 'Github 博客'
    url: 'https://zywj0han9.github.io/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false

  - id: CF-Blog-zywj0han9
    name: Cloudflare 博客
    description: 'Cloudflare 博客'
    url: 'https://blog.zywj0han9.win/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: false # should fetch follow redirects, default=false
    
